---
- name: install yum packages
  yum: name={{ item }} state=latest
  with_items:
  - "{{ os_packages }}"

- name: disable selinux
  selinux: state=disabled
  notify: change selinux
  with_first_found:
    - files:
      - /etc/selinux/config
      skip: true

#- name: change resolv to google public DNS
#  template: src=resolv.conf.j2 dest=/etc/resolv.conf

- name: configure timezone to to Asia/Tokyo
  timezone: 
    name: Asia/Tokyo