---
# install nginx

- name: install yum remi repo
  yum: name={{ item }} state=present
  with_items:
  - "{{ remirepo_url }}"

- name: install yum nginx % php 7.1
  yum: name={{ item }} state=latest
  with_items:
  - "{{ httpd_packages }}"

- name: configure nginx.conf
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: change nginx

